azure:
  activedirectory:
    b2c:
      tenant: onlexnet
      client-id: 9027d226-b538-414e-82ea-abfe306461ad # SinNet
      client-secret: ${AZURE_APP_SECRET}
      reply-url: http://localhost:3000/reply
      user-flows:
        sign-up-or-sign-in: B2C_1_sign-in-or-up
        # profile-edit: ${your-profile-edit-user-flow}     # optional
        # password-reset: ${your-password-reset-user-flow} # optional

# because I use spring-boot:run to run application from sources, my expectation is application does
# restart when some of modules are updated. To make it happen, Spring plugin shpouldshould be aware
# where are resources which should trigger restarting applicationm, when changed.
# The list below should cover all modules where we keep sources expected to restart application, when changed.
spring:
    devtools:
        restart:
            additional-paths=../web-graphql,../domain-api,../domain-core

graphql:
    servlet:
        corsEnabled=true
