azure:
  activedirectory:
    client-id: d6f91b94-e8c7-4ab7-b198-fc97a6b1741a
    client-secret: ${AZURE_APP_SECRET}
    user-group:
      allowed-groups:
      - group1
      - group2
# azure:
#   activedirectory:
#     b2c:
#       tenant: LexNet
#       client-id: d6f91b94-e8c7-4ab7-b198-fc97a6b1741a
#       client-secret: ${AZURE_APP_SECRET}
#       reply-url: http://localhost:3000
#       logout-success-url: http://localhost:3000/logout
#       user-flows:
#         sign-up-or-sign-in: B2C_1_sign-up-in
#         # profile-edit: ${your-profile-edit-user-flow}     # optional
#         # password-reset: ${your-password-reset-user-flow} # optional

# because I use spring-boot:run to run application from sources, my expectation is application does
# restart when some of modules are updated. To make it happen, Spring plugin shpouldshould be aware
# where are resources which should trigger restarting applicationm, when changed.
# The list below should cover all modules where we keep sources expected to restart application, when changed.
spring:
    devtools:
        restart:
            additional-paths=../web-graphql,../domain-api,../domain-core

graphql:
    servlet:
        corsEnabled=true

# azure:
#     activedirectory.client-id=d6f91b94-e8c7-4ab7-b198-fc97a6b1741a
# azure.activedirectory.client-secret=${AZURE_APP_SECRET}
# azure.activedirectory.ActiveDirectoryGroups=group1,group2
