# because I use spring-boot:run to run application from sources, my expectation is application does
# restart when some of modules are updated. To make it happen, Spring plugin shpouldshould be aware
# where are resources which should trigger restarting applicationm, when changed.
# The list below should cover all modules where we keep sources expected to restart application, when changed.
spring:
    devtools:
        restart:
            additional-paths: ../web-server,../web-graphql,../domain-api,../domain-core
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: true
                web-allow-others: true

    datasource:
        username: sa
        password:
        url: jdbc:h2:mem:db
        driver-class-name: org.h2.Driver
    
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create-drop

management:
    metrics:
        binders:
            jvm:
                enabled: true      

graphql:
    servlet:
        corsEnabled: true
