#  Not sure if th config should be placed locally, or in shared part of DAPR

# https://docs.dapr.io/operations/monitoring/tracing/supported-tracing-backends/zipkin/

apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  metrics:
    enabled: true

---

# https://docs.dapr.io/operations/monitoring/tracing/supported-tracing-backends/jaeger/

# apiVersion: dapr.io/v1alpha1
# kind: Configuration
# metadata:
#   name: daprConfig
#   namespace: default
# spec:
#   tracing:
#     samplingRate: "1"
#     zipkin:
#       endpointAddress: "http://localhost:9411/api/v2/spans"
#   metrics:
#     enabled: true

---

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
