#  Not sure if th config should be placed locally, or in shared part of DAPR

# apiVersion: dapr.io/v1alpha1
# kind: Configuration
# metadata:
#   name: daprConfig
#   namespace: default
# spec:
#   tracing:
#     samplingRate: "1"
#     zipkin:
#       endpointAddress: "http://localhost:9411/api/v2/spans"
#   metrics:
#     enabled: true

---

# https://docs.dapr.io/operations/monitoring/tracing/supported-tracing-backends/jaeger/

# apiVersion: dapr.io/v1alpha1
# kind: Configuration
# metadata:
#   name: daprConfig
#   namespace: default
# spec:
#   tracing:
#     samplingRate: "1"
#     zipkin:
#       endpointAddress: "http://localhost:9412/api/v2/spans"
#   metrics:
#     enabled: true
