# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-12T18:15:44+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, Field


class Status(StrEnum):
    """
    Current health status of the service
    """

    ok = 'ok'
    degraded = 'degraded'
    unhealthy = 'unhealthy'


class HealthResponse(BaseModel):
    status: Status = Field(
        ..., description='Current health status of the service', examples=['ok']
    )
    service: str = Field(
        ..., description='Service identifier', examples=['app_raport1']
    )


class ReportSummary(BaseModel):
    hours: float = Field(
        ..., description='Total hours across all entries', examples=[40.0], ge=0.0
    )
    billable_amount: float = Field(
        ...,
        alias='billableAmount',
        description='Total billable amount in the report currency',
        examples=[5000.0],
        ge=0.0,
    )
    entries: int = Field(
        ..., description='Count of line items in the report', examples=[5], ge=0
    )


class ReportItem(BaseModel):
    day: date = Field(
        ..., description='Date of the time entry (YYYY-MM-DD)', examples=['2026-01-05']
    )
    project: str = Field(
        ..., description='Project name or identifier', examples=['Internal']
    )
    hours: float = Field(
        ..., description='Hours worked on this day/project', examples=[8.0], ge=0.0
    )
    rate: float = Field(
        ..., description='Hourly rate for this entry', examples=[125.0], ge=0.0
    )
    amount: float = Field(
        ..., description='Calculated amount (hours × rate)', examples=[1000.0], ge=0.0
    )


class ReportResponse(BaseModel):
    report_id: str = Field(
        ...,
        alias='reportId',
        description='Unique identifier for the report',
        examples=['sample-001'],
    )
    generated_at: AwareDatetime = Field(
        ...,
        alias='generatedAt',
        description='ISO 8601 timestamp when the report was generated',
        examples=['2026-01-01T00:00:00Z'],
    )
    currency: str = Field(
        ...,
        description='Currency code for all monetary amounts',
        examples=['PLN'],
        pattern='^[A-Z]{3}$',
    )
    summary: ReportSummary
    items: list[ReportItem] = Field(
        ..., description='Individual report line items', min_length=0
    )
