resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: "sinnet-acr"
  imageName: "uservice-customers"
  containerRegistry: "sinnetapps.azurecr.io"
  dockerRepository: onlex-sinnet-reports

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - uservice-customers

pr:
  branches:
    include:
      - master
  paths:
    include:
      - uservice-customers

jobs:
  - job: CICD
    displayName: CI/CD build
    pool:
      vmImage: ubuntu-latest

    steps:

      - task: Gradle@2
        inputs:
          displayName: 'Project compilation with Gradle'
          gradleWrapperFile: 'uservice-customers/main/gradlew' 
          cwd: 'uservice-customers/main'
          #options: # Optional
          #tasks: 'build' # A list of tasks separated by spaces, such as 'build test'
          publishJUnitResults: true 
          testResultsFiles: '**/TEST-*.xml' # Required when publishJUnitResults == True
          #testRunTitle: # Optional
          #codeCoverageToolOption: 'None' # Optional. Options: none, cobertura, jaCoCo
          #codeCoverageClassFilesDirectories: 'build/classes/main/' # Required when codeCoverageToolOption == False
          #codeCoverageClassFilter: # Optional. Comma-separated list of filters to include or exclude classes from collecting code coverage. For example: +:com.*,+:org.*,-:my.app*.*
          #codeCoverageFailIfEmpty: false # Optional
          #javaHomeOption: 'JDKVersion' # Options: jDKVersion, path
          jdkVersionOption: '1.11'
          #jdkDirectory: # Required when javaHomeOption == Path
          #jdkArchitectureOption: 'x64' # Optional. Options: x86, x64
          #gradleOptions: '-Xmx1024m' # Optional
          #sonarQubeRunAnalysis: false 
          #sqGradlePluginVersionChoice: 'specify' # Required when sonarQubeRunAnalysis == True# Options: specify, build
          #sonarQubeGradlePluginVersion: '2.6.1' # Required when sonarQubeRunAnalysis == True && SqGradlePluginVersionChoice == Specify
          checkStyleRunAnalysis: false # Optional
          #findBugsRunAnalysis: false # Optional
          #pmdRunAnalysis: false # Optional

      - task: Docker@2
        displayName: Build uservice image
        inputs:
          command: build
          dockerfile: uservice-customers/Dockerfile
          buildContext: uservice-customers
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(dockerRepository)
          tags: |
            $(Build.SourceBranchName)-$(Build.BuildNumber)

      - task: Docker@2
        displayName: Push webapi image to docker ACR
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
        inputs:
          command: push
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(dockerRepository)
          tags: |
            $(Build.SourceBranchName)-$(Build.BuildNumber)

