/**
 * All application events generated by aplication
 * <p>
 * Right now there is not too much application events, maybe later on separated
 * packages will be introduced.
 *
 * @since 0.1
 * @author siudeks
 */

package sinnet.appevents;
