# https://hub.docker.com/_/postgres/

version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    network_mode: "host"
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=sinnet
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    
