resources:
  - repo: self

variables:
  # well-known connection, defined manually.
  # The connection used in pipeline allows to access to ACR sinnet.azurecr.io
  dockerRegistryServiceConnection: "sinnet-acr"
  # image name (without tags) used to build final image
  imageName: "uservice-webapi"
  # name of the registry where the image is hosted on.
  # in Docker world, it is also part of image name (prefix)
  containerRegistry: "sinnetapps.azurecr.io"

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      # We have to include all folders where source files are located
      - /uservice-webapi/

jobs:
  - job: CICD
    displayName: Webapi CI/CD build
    pool:
      vmImage: ubuntu-latest

    steps:
      - bash: |
          echo "##vso[task.setvariable variable=my_version]$(cat .version)"
        workingDirectory: webapi
        displayName: Read version from .version file

      - task: Maven@3
        displayName: 'Project compilation with Maven'
        inputs:
          mavenPomFile: 'webapi/main/pom.xml'
          goals: 'verify'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          # options:
          #  - disable log entries (a lot of entries) related to artifacts downloaded by maven
          options: -B --no-transfer-progress
          sonarQubeRunAnalysis: false
          sqMavenPluginVersionChoice: 'latest' # Required when sonarQubeRunAnalysis == True# Options: latest, pom
          checkStyleRunAnalysis: true # We use checkstyle in coding, so let's use it with Maven as well

      - task: Docker@2
        displayName: Build webapi image
        inputs:
          command: build
          dockerfile: webapi/Dockerfile
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: webapi
          # to use inside docker variable do use version with build
          # lets put them from just obtained value from .version file
          arguments: --build-arg REVISION=$(my_version)
          tags: |
            $(Build.SourceBranchName)-$(Build.BuildNumber)

      - task: Docker@2
        displayName: Push webapi image to docker ACR
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
        inputs:
          command: push
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: webapi
          tags: |
            $(Build.SourceBranchName)-$(Build.BuildNumber)

