resources:
  - repo: self

variables:
  workingDirectory: libs-java
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#maven
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  cacheName: $(Build.DefinitionName)

trigger:
  batch: true
  branches:
    include:
      - master

  paths:
    include:
      # We have to include all folders where source files are located
      - libs-java

pr:
  branches:
    include:
      - master
  paths:
    include:
      # We have to include all folders where source files are located
      - libs-java

jobs:
  - job: CI
    displayName: Build and (optionally deploy) shared Libs
    pool:
      vmImage: ubuntu-latest

    steps:

      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | "$(cacheName)"'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)
        displayName: Cache Maven local repo

      - bash: |
          echo "##vso[task.setvariable variable=SEMVERSION]$(cat .semversion)"
        workingDirectory: $(workingDirectory)
        displayName: Read version from .semversion file

      # Maven Authenticate v0
      # Provides credentials for Azure Artifacts feeds and external maven repositories.
      - task: MavenAuthenticate@0
        inputs:
          artifactsFeeds: sinnet
          #mavenServiceConnections: # string. Credentials for repositories outside this organization/collection

      - task: Maven@4
        displayName: 'Maven install: Libs'
        inputs:
          mavenPomFile: 'libs-java/pom.xml'
          goals: deploy
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          mavenAuthenticateFeed: true
          options: >
            $(MAVEN_OPTS)
            -Drevision=$(SEMVERSION)
            -B
            --no-transfer-progress
          sonarQubeRunAnalysis: false
          checkStyleRunAnalysis: false
