schema: ../../uservice-webapi/api.graphql/**/*.graphql
documents: 'src/**/*.graphql'
generates:
  src/Components/.generated/components.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
      withComponent: false
      withHOC: false
