from typing import Any

from . import Context, HttpRequest, HttpResponse

class AsgiMiddleware:
    def __init__(self, app: Any) -> None: ...
    def handle(self, req: HttpRequest, context: Context | None = ...) -> HttpResponse: ...
    async def handle_async(self, req: HttpRequest, context: Context | None = ...) -> HttpResponse: ...
    def __call__(self, scope: Any, receive: Any, send: Any) -> Any: ...
