[mypy]
python_version = 3.13
strict = True
warn_unused_configs = True
show_error_codes = True
pretty = True
files = function_app.py, tests

# Wymaganie używania hintów typów
disallow_untyped_defs = True
disallow_untyped_calls = True
disallow_incomplete_defs = True
disallow_untyped_decorators = True
check_untyped_defs = True

[mypy-azure.functions.*]
ignore_missing_imports = True
