apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    # kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    cert-manager.io/issuer: {{ include "letsencrypt.instance" . }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - {{ include "ingress.host" . }}
    secretName: portal-tls-secret
  rules:
  - host: {{ include "ingress.host" . }}
    http:
      paths:
        - path: /hello
          pathType: Prefix
          backend:
            service:
              name: uservice-webapi-svc
              port:
                number: 8080
        - path: /q/graphql-ui
          pathType: Prefix
          backend:
            service:
              name: uservice-webapi-svc
              port:
                number: 8080
        - path: /graphql
          pathType: Prefix
          backend:
            service:
              name: uservice-webapi-svc
              port:
                number: 8080
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: uservice-webapi-svc
              port:
                number: 8080

        - path: /
          pathType: Prefix
          backend:
            service:
              name: webapp-svc
              port:
                number: 80
                