apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sinnet
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/issuer: {{ include "letsencrypt.instance" . }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  tls:
  - hosts:
    - {{ include "ingress.host" . }}
    secretName: portal-tls-secret
  rules:
  - host: {{ include "ingress.host" . }}
    http:
      paths:
        - path: /graphiql
          pathType: Prefix
          backend:
            service:
              name: uservice-webapi-svc
              port:
                number: 8080
        - path: /graphql
          pathType: Prefix
          backend:
            service:
              name: uservice-webapi-svc
              port:
                number: 8080
        - path: /actuator
          pathType: Prefix
          backend:
            service:
              name: uservice-webapi-svc
              port:
                number: 8080
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: uservice-webapi-svc
              port:
                number: 8080

        - path: /
        # https://stackoverflow.com/questions/60579877/nginx-returns-index-html-content-for-all-angular-files-including-scripts
        # - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: uservice-ui
              port:
                number: 80

