apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservice-projects
  labels:
    app: uservice-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uservice-projects
  
  template:
    metadata:
      labels:
        app: uservice-projects
      annotations:
        # https://docs.dapr.io/reference/arguments-annotations-overview/
        dapr.io/enabled: "true"
        dapr.io/app-id: "uservice-projects-app-id"
        dapr.io/app-port: "8080"
        dapr.io/app-protocol: grpc

    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: initdb
          image: uservice-projects-initdb:{{ required "Tag of onlex-sinnet-projects image has to be provided" .Values.imageProjectsTag }}
          imagePullPolicy: Never
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_host
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_port
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_name
          - name: DATABASE_SCHEMA
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_schema
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_password
      containers:
        - name: host
          # image: sinnet.azurecr.io/uservice-projects-host:{{ required "Tag of onlex-sinnet-projects image has to be provided" .Values.imageProjectsTag }}
          image: uservice-projects-host:{{ required "Tag of onlex-sinnet-projects image has to be provided" .Values.imageProjectsTag }}
          # when use local docker image: Never to use locally build image, or Always when working on real k8s environment
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_host
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_port
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_name
          - name: DATABASE_SCHEMA
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_schema
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_password
