apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-dep
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  
  template:
    metadata:
      labels:
        app: webapi
    
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: webapi
          image: sinnet.azurecr.io/webapi::{{ required "Tag of WebApi image has to be provided" .Values.imageWebApiTag }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          - name: APP_DB_HOST
            value: {{ .Values.databaseHost }}
          - name: APP_DB_NAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_name
          - name: APP_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_username
          - name: APP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: services_database_password
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: appinsight_connection_string
