apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservice-timeentries-dep
  labels:
    app: uservice-timeentries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uservice-timeentries
  
  template:
    metadata:
      labels:
        app: uservice-timeentries
    
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: uservice-timeentries-initdb
          image: sinnet.azurecr.io/uservice-timeentries-initdb:{{ required "Tag of uservice-timeentries image has to be provided" .Values.imageUserviceTimeEntriesTag }}
      containers:
        - name: uservice-timeentries
          image: sinnet.azurecr.io/uservice-timeentries:{{ required "Tag of uservice-timeentries image has to be provided" .Values.imageUserviceTimeEntriesTag }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
