# We need node 16 to work (hence 1-16-bullseye)
# TODO: migrate to node20
# https://github.com/devcontainers/templates/blob/main/src/javascript-node/README.md
FROM mcr.microsoft.com/devcontainers/typescript-node:1-16-bullseye
