
variables:
  dockerRegistryServiceConnection: "sinnet-acr"
  imageName: "uservice-customers"
  containerRegistry: "sinnetapps.azurecr.io"
  dockerRepository: onlex-sinnet-reports

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
  - pipeline: helm_CI
    project: sinnet
    source: onlex-sinnet-helm
    trigger: true
    branch: master


trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /deploy/

# Currently we don't need any deployment when PR is created
pr: none # Disable pull request triggers.

stages:
  - stage: DownloadHelmStage
    displayName: Download HELM definition
    jobs:
    - job: DownloadHelmJob
      steps:
      - checkout: none
      - download: helm_CI
        artifact: chart
      - bash: |
          # variable: var_chart_file_name is used to keep name of latests char name build on latest version of images
          # isoutput=true is required to make variable visible in invoked templates
          echo "##vso[task.setvariable variable=var_chart_file_name;isoutput=true]$(cat $(Pipeline.Workspace)/helm_CI/chart/chart.config | jq -r '.chartFileName')"
        name: ExtractChartFilenameStep
        displayName: Extract Chart filename
      - bash: |
          echo DEBUG $(ExtractChartFilenameStep.var_chart_file_name)
        displayName: DEBUG Display name of the chart

  - template: deploy-to-env.yaml
    dependsOn: DownloadHelmStage
    parameters:
      envName: DEV01
      chartFileName: $[ stageDependencies.DownloadHelmStage.DownloadHelmJob.outputs['ExtractChartFilenameStep.var_chart_file_name'] ]

  - template: deploy-to-env.yaml
    dependsOn: DownloadHelmStage
    parameters:
      envName: STG01
      chartFileName: $[ stageDependencies.DownloadHelmStage.DownloadHelmJob.outputs['ExtractChartFilenameStep.var_chart_file_name'] ]


  # - stage: deployToStg
  #   displayName: Deploy HELM Chart to STG
  #   jobs:
  #     - deployment: deployToStg
  #       displayName: Deploy to STG01
  #       environment:
  #         name: STG01
  #         resourceType: Kubernetes
  #       strategy:                  
  #         runOnce:
  #           deploy:
  #             steps:
  #               - checkout: none
  #               - download: helm_CI
  #                 artifact: chart
  #               - bash: |
  #                   echo "##vso[task.setvariable variable=var_chart_file_name]$(cat $(Pipeline.Workspace)/helm_CI/chart/chart.config | jq '.chartFileName')"
  #               - bash: |
  #                   echo $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
  #               - task: HelmDeploy@0
  #                 displayName: Helm install
  #                 inputs:
  #                   kubernetesServiceEndpoint: onlex-sinnet-stg01
  #                   command: upgrade
  #                   install: true
  #                   chartName: $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
  #                   arguments: -f $(Pipeline.Workspace)/helm_CI/chart/config.yaml
  #                   releaseName: sinnet-reports
  #                   namespace: onlex-sinnet-stg01

  - stage: deployToProd
    displayName: Deploy HELM Chart to PROD
    jobs:
      - deployment: deployToPrd
        displayName: Deploy to PRD01
        environment:
          name: PRD01
          resourceType: Kubernetes
        strategy:                  
          runOnce:
            deploy:
              steps:
                - checkout: none
                - download: helm_CI
                  artifact: chart
                - bash: |
                    echo "##vso[task.setvariable variable=var_chart_file_name]$(cat $(Pipeline.Workspace)/helm_CI/chart/chart.config | jq '.chartFileName')"
                - bash: |
                    echo $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                - task: HelmDeploy@0
                  displayName: Helm install
                  inputs:
                    kubernetesServiceEndpoint: onlex-sinnet-prd01
                    namespace: onlex-sinnet-prd01
                    command: upgrade
                    install: true
                    chartName: $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                    arguments: -f $(Pipeline.Workspace)/helm_CI/chart/config.yaml
                    releaseName: sinnet-reports
