# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /deploy/
pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: webapp
      type: ACR  
      azureSubscription: onlex-sinnet-prod
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: webapp
      trigger: "true"

# steps:
# - script: echo |
#     echo $(resources.container.webapp.type)
#     echo $(resources.container.webapp.registry)
#     echo $(resources.container.webapp.repository)
#     echo $(resources.container.webapp.tag)
#     echo $(resources.container.webapp.digest)
#     echo $(resources.container.webapp.URI)
#     echo $(resources.container.webapp.location)

stages:
  - stage:
    displayName: CD
    jobs:
      - deployment: DeployWeb
        displayName: WebApp
        # creates an environment if it doesn't exist
        environment: 'onlex-sinnet-stg'
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - bash: echo $(resources.container.webapp.tag)
              - task: KubernetesManifest@0
                displayName: Deploy to Kubernetes cluster
                inputs:
                  action: deploy
                  rolloutStatusTimeout: 60
                  kubernetesServiceConnection: sinnet-microk8s
                  namespace: onlex-sinnet-stg
                  manifests: |
                    deploy/main/*
                  imagePullSecrets: |
                    $(imagePullSecret)
                  containers: |
                      sinnet.azurecr.io/webapp:$(resources.container.webapp.tag)
