
variables:
  dockerRegistryServiceConnection: "sinnet-acr"
  imageName: "uservice-customers"
  containerRegistry: "sinnetapps.azurecr.io"
  dockerRepository: onlex-sinnet-reports

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
  - pipeline: helm_CI
    project: sinnet
    source: onlex-sinnet-helm
    trigger: true


trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /deploy/
pr:
  branches:
    exclude:
      - '*'


stages:
  - stage: deployToDev01
    displayName: Deploy HELM Chart to DEV01
    jobs:
      - deployment: deployToDev01
        displayName: Deploy to DEV01
        environment:
          name: DEV01
          resourceType: Kubernetes
        strategy:                  
          runOnce:
            deploy:
              steps:
                - checkout: none
                - download: helm_CI
                  artifact: chart
                - bash: |
                    echo "##vso[task.setvariable variable=var_chart_file_name]$(cat $(Pipeline.Workspace)/helm_CI/chart/chart.config | jq '.chartFileName')"
                - bash: |
                    echo $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                - task: HelmDeploy@0
                  displayName: Helm install
                  inputs:
                    kubernetesServiceEndpoint: onlex-sinnet-dev01
                    namespace: onlex-sinnet-dev01
                    command: upgrade
                    install: true
                    chartName: $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                    arguments: -f $(Pipeline.Workspace)/helm_CI/chart/config.yaml
                    releaseName: sinnet-reports

  - stage: deployToStg
    displayName: Deploy HELM Chart to STG
    jobs:
      - deployment: deployToStg
        displayName: Deploy to STG01
        environment:
          name: STG01
          resourceType: Kubernetes
        strategy:                  
          runOnce:
            deploy:
              steps:
                - checkout: none
                - download: helm_CI
                  artifact: chart
                - bash: |
                    echo "##vso[task.setvariable variable=var_chart_file_name]$(cat $(Pipeline.Workspace)/helm_CI/chart/chart.config | jq '.chartFileName')"
                - bash: |
                    echo $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                - task: HelmDeploy@0
                  displayName: Helm install
                  inputs:
                    kubernetesServiceEndpoint: onlex-sinnet-stg01
                    command: upgrade
                    install: true
                    chartName: $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                    arguments: -f $(Pipeline.Workspace)/helm_CI/chart/config.yaml
                    releaseName: sinnet-reports
                    namespace: onlex-sinnet-stg01

  - stage: deployToProd
    displayName: Deploy HELM Chart to PROD
    jobs:
      - deployment: deployToPrd
        displayName: Deploy to PRD01
        environment:
          name: PRD01
          resourceType: Kubernetes
        strategy:                  
          runOnce:
            deploy:
              steps:
                - checkout: none
                - download: helm_CI
                  artifact: chart
                - bash: |
                    echo "##vso[task.setvariable variable=var_chart_file_name]$(cat $(Pipeline.Workspace)/helm_CI/chart/chart.config | jq '.chartFileName')"
                - bash: |
                    echo $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                - task: HelmDeploy@0
                  displayName: Helm install
                  inputs:
                    kubernetesServiceEndpoint: onlex-sinnet-prd01
                    namespace: onlex-sinnet-prd01
                    command: upgrade
                    install: true
                    chartName: $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                    arguments: -f $(Pipeline.Workspace)/helm_CI/chart/config.yaml
                    releaseName: sinnet-reports
