pool:
  vmImage: 'ubuntu-latest'


resources:
  pipelines:
  - pipeline: webapp_CI
    project: sinnet
    source: onlex-sinnet-webapp
    trigger:
      branches:
        include:
        - master
  - pipeline: webapi_CI
    project: sinnet
    source: onlex-sinnet-webapi
    trigger:
      branches:
        include:
        - master
  - pipeline: report_CI
    project: sinnet
    source: onlex-sinnet-reports
    trigger:
      branches:
        include:
        - master
  - pipeline: manifest_CI
    project: sinnet
    source: onlex-sinnet-manifest
    trigger:
      branches:
        include:
        - master
  containers:
    - container: webapp
      type: ACR  
      azureSubscription: sinnet-default-manual-arm
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: webapp
    - container: webapi
      type: ACR  
      azureSubscription: sinnet-default-manual-arm
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: webapi
    - container: reports
      type: ACR  
      azureSubscription: sinnet-default-manual-arm
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: onlex-sinnet-reports

stages:
  - stage:
    displayName: CD
    jobs:
      - deployment: DeployAppComponents
        displayName: Deploy app components
        environment: 'onlex-sinnet-prd'
        strategy:
          runOnce:
            deploy:
              steps:
              - bash: echo $(resources.container.webapp.tag)
              - task: DownloadPipelineArtifact@2
                displayName: Download Manifest
                inputs:
                  source: specific
                  project: sinnet
                  pipeline: onlex-sinnet-manifest
                  preferTriggeringPipeline: true
                  #runVersion: 'latest' # Required when source == Specific# Options: latest, latestFromBranch, specific
                  #runBranch: 'refs/heads/master' # Required when source == Specific && RunVersion == LatestFromBranch
                  #runId: # Required when source == Specific && RunVersion == Specific
                  #tags: # Optional
                  #artifact: # Optional
                  #patterns: '**' # Optional
                  #path: '$(Pipeline.Workspace)' 
              - bash: ls -l
              - task: KubernetesManifest@0
                displayName: Create secret
                inputs: 
                  action: createSecret
                  secretType: dockerRegistry
                  secretName: regcred
                  dockerRegistryEndpoint: sinnet-acr
                  kubernetesServiceConnection: sinnet-microk8s
                  namespace: onlex-sinnet-prd
              - checkout: self
              - task: KubernetesManifest@0
                displayName: Deploy to Kubernetes cluster
                inputs:
                  action: deploy
                  # rolloutStatusTimeout: 60
                  kubernetesServiceConnection: sinnet-microk8s
                  namespace: onlex-sinnet-prd
                  manifests: |
                    deploy/main/*
                  containers: |
                      sinnet.azurecr.io/webapp:$(resources.container.webapp.tag)
                      sinnet.azurecr.io/webapi:$(resources.container.webapi.tag)
                      sinnet.azurecr.io/onlex-sinnet-reports:$(resources.container.reports.tag)
