# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /deploy/
pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: webapp
      type: ACR  
      azureSubscription: sinnet-default-manual-arm
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: webapp
      trigger: "true"
    - container: webapi
      type: ACR  
      azureSubscription: sinnet-default-manual-arm
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: webapi
      trigger: "true"

stages:
  - stage:
    displayName: CD
    jobs:
      - deployment: DeployWeb
        displayName: WebApp
        environment: 'sinnet-microk8s'
        strategy:
          runOnce:
            deploy:
              steps:
              - bash: echo $(resources.container.webapp.tag)
              - task: KubernetesManifest@0
                displayName: Create secret
                inputs: 
                  action: createSecret
                  secretType: dockerRegistry
                  secretName: regcred
                  dockerRegistryEndpoint: sinnet-acr
                  kubernetesServiceConnection: sinnet-microk8s
                  namespace: onlex-sinnet-prd
              - checkout: self
              - task: KubernetesManifest@0
                displayName: Deploy to Kubernetes cluster
                inputs:
                  action: deploy
                  # rolloutStatusTimeout: 60
                  kubernetesServiceConnection: sinnet-microk8s
                  namespace: onlex-sinnet-prd
                  manifests: |
                    deploy/main/*
                  containers: |
                      sinnet.azurecr.io/webapp:$(resources.container.webapp.tag)
                      sinnet.azurecr.io/webapi:$(resources.container.webapi.tag)
