# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /deploy/
pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: webapp
      type: ACR  
      azureSubscription: onlex-sinnet-prod
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: webapp
      trigger: "true"
      image: webapp

stages:
  - stage: 
    displayName: Test variables
    jobs:
      - job: 
        steps:
        - script: echo $(System.DefaultWorkingDirectory)
          displayName: Test container variables (TAG)
  - stage:
    displayName: CD
    jobs:
      - deployment: DeployWeb
        displayName: WebApp
        environment: 'sinnet-microk8s'
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - task: KubernetesManifest@0
                displayName: Deploy to Kubernetes cluster
                inputs:
                  action: deploy
                  rolloutStatusTimeout: 60
                  kubernetesServiceConnection: sinnet-microk8s
                  namespace: onlex-sinnet-stg
                  manifests: |
                    deploy/main/*
                  imagePullSecrets: |
                    $(imagePullSecret)
                  containers: |
                      sinnet.azurecr.io/webapp:$(resources.container.webapp.tag)
