parameters:
- name: envName # name of the environment (DEV01, STG01, PRD01)
  type: string # data type of the parameter; required
  default: false

variables:
   envNameLower: ${{ lower(parameters.envName) }}

stage: deployToDev01
displayName: Deploy HELM Chart to ${{ parameters.envName }}
jobs:
  - deployment: deployToStg
    displayName: Deploy to ${{ parameters.envName }}
    environment:
      name: ${{ parameters.envName }}
      resourceType: Kubernetes
    strategy:                  
      runOnce:
        deploy:
          steps:
            - checkout: none
            - download: helm_CI
              artifact: chart
            - bash: |
                echo "##vso[task.setvariable variable=var_chart_file_name]$(cat $(Pipeline.Workspace)/helm_CI/chart/chart.config | jq '.chartFileName')"
            - bash: |
                echo $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
            - task: HelmDeploy@0
              displayName: Helm install
              inputs:
                kubernetesServiceEndpoint: onlex-sinnet-$(envNameLower)
                command: upgrade
                install: true
                chartName: $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                arguments: -f $(Pipeline.Workspace)/helm_CI/chart/config.yaml
                releaseName: sinnet-reports
                namespace: onlex-sinnet-$(envNameLower)