parameters:
- name: envName # name of the environment (DEV01, STG01, PRD01)
  type: string # data type of the parameter; required
  values:
  - DEV01
  - STG01
  - PRD01
- name: chartFileName
  type: string

stages:
- stage: deployToEnvironment${{ parameters.envName }}
  dependsOn: DownloadHelmStage
  variables:
    # we use lowercase name of the environment as part of kubernetes namespace
    envNameLower: ${{ lower(parameters.envName) }}
    # we use uppercase for Azure DevOps environment name
    # Currently the same as parameter (all allowed env names in parameters are capitalized), but it makes us independent of
    # env name capitalization in parameters
    envNameUpper: ${{ upper(parameters.envName) }}

    var_chart_file_name: ${{ parameters.chartFileName }}
  displayName: Deploy HELM Chart to ${{ variables.envNameUpper }}
  jobs:
    - deployment: deployTo
      displayName: Deploy to ${{ variables.envNameUpper }}
      environment:
        name: ${{ variables.envNameUpper }}
        # Below commented as we can't point Kubernetes as it is not created using Terraform scripts yed
        # The closest issue about resources in environment mentioned here https://github.com/microsoft/terraform-provider-azuredevops/issues/143
        # resourceType: Kubernetes
      strategy:                  
        runOnce:
          deploy:
            steps:
              - bash: |
                  echo $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                displayName: DEBUG Display fill chart filename (1)
              - task: HelmDeploy@0
                displayName: Helm install 2
                inputs:
                  kubernetesServiceEndpoint: onlex-sinnet-${{ variables.envNameLower }}
                  command: upgrade
                  install: true
                  chartName: $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                  arguments: -f $(Pipeline.Workspace)/helm_CI/chart/config.yaml
                  releaseName: sinnet-reports
                  namespace: onlex-sinnet-${{ variables.envNameLower }}