parameters:
- name: envName # name of the environment (DEV01, STG01, PRD01)
  type: string # data type of the parameter; required
  default: false

stages:
- stage: deployToEnvironment
  variables:
    envNameLower: ${{ lower(parameters.envName) }}
    envNameUpper: ${{ upper(parameters.envName) }}
  displayName: Deploy HELM Chart to DEV01
  jobs:
    - deployment: deployTo
      displayName: Deploy to DEV01 ${{ variables.envNameUpper }}
      environment:
        name: ${{ variables.envNameUpper }}
        # Below commented as we can't point Kubernetes as it is not created using Terraform scripts yed
        # The closes issue about resources in environment mentioned here https://github.com/microsoft/terraform-provider-azuredevops/issues/143
        # resourceType: Kubernetes
      strategy:                  
        runOnce:
          deploy:
            steps:
              - checkout: none
              - download: helm_CI
                artifact: chart
              - bash: |
                  echo "##vso[task.setvariable variable=var_chart_file_name]$(cat $(Pipeline.Workspace)/helm_CI/chart/chart.config | jq '.chartFileName')"
              - bash: |
                  echo $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
              - task: HelmDeploy@0
                displayName: Helm install
                inputs:
                  kubernetesServiceEndpoint: onlex-sinnet-dev01
                  command: upgrade
                  install: true
                  chartName: $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                  arguments: -f $(Pipeline.Workspace)/helm_CI/chart/config.yaml
                  releaseName: sinnet-reports
                  namespace: onlex-sinnet-dev01