# some configuration copied from https://docs.microsoft.com/en-us/azure/aks/ingress 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: psa-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    
    # Rewriting can be useful later on, let's go back later on
    # https://kubernetes.github.io/ingress-nginx/examples/rewrite/README/
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - raport.sin.net.pl
    secretName: tls-secret
  rules:
  - host: raport.sin.net.pl
    http:
      paths:
      - path: /graphql
        backend:
          serviceName: backend-svc
          servicePort: 8080
      - path: /graphiql
        backend:
          serviceName: backend-svc
          servicePort: 8080
      - path: /api
        backend:
          serviceName: backend-svc
          servicePort: 8080
