apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /apple
          backend:
            serviceName: apple-service
            servicePort: 5678
        - path: /banana
          backend:
            serviceName: banana-service
            servicePort: 5678

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ingress
#   labels:
#     app: nginx-ingress
# spec:
#   type: LoadBalancer
#   ports:
#   - name: http
#     port: 80
#     targetPort: 80
#   - name: https
#     port: 443
#     targetPort: 443
#   selector:
#     app: nginx-ingress