apiVersion: v1
kind: ReplicationController
metadata:
  name: storage-rc
spec:
  replicas: 1
  selector:
    io.kompose.service: storage
  template:
    metadata:
      labels:
        zone: prod
        version: snapshot
        io.kompose.service: storage
    spec:
      containers:
        - name: storage
          image: mongo:3.6
          ports:
          - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: storage-svc
  labels:
    io.kompose.service: storage
spec:
  type: NodePort
  ports:
  - port: 27017
  selector:
    io.kompose.service: storage
