ARG APP_ENV=dev

#---
FROM mcr.microsoft.com/java/jdk:17u7-zulu-alpine as build
WORKDIR app

COPY . .
COPY /host/src/main/jib/ /

RUN /.mvnw clean compile --no-transfer-progress -Dcheckstyle.skip

EXPOSE 11021
ENV SPRING_PROFILES_ACTIVE=inmemory
ENTRYPOINT ["./mvnw", "-pl", "host", "-am", "spring-boot:run", "-Dcheckstyle.skip"]
