# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - deployment
pool:
  vmImage: 'ubuntu-latest'


steps:
- publish: deployment/main
  artifact: manifest