schema: 
  - http://127.0.0.1:8000/graphql/
  - src/my-client-schema.graphql
overwrite: true
documents:
  - ./src/**/*.tsx
  - ./src/**/*.graphql
generates:
  ./src/schema-types.d.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
