apiVersion: v1
kind: Service
metadata:
  name: host
  labels:
    app: host
spec:
  ports:
  - port: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: host
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host
  labels:
    app: host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host
  template:
    metadata:
      labels:
        app: host
    spec:
      containers:
      - name: host
        image: host
