# Inspired by https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker/
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      SA_PASSWORD: "${DATABASE_PASSWORD}"
      ACCEPT_EULA: "Y"

  daprd:
    image: "daprio/daprd:1.12.3-mariner"
    restart: always
    command: [
      # https://v1-7.docs.dapr.io/reference/arguments-annotations-overview/
      "./daprd",
      "--app-id", "uservice-webapp",
      "--app-port", "8080",
      "--dapr-grpc-port", "${DAPR_GRPC_PORT}",
      "--dapr-http-port", "${DAPR_HTTP_PORT}",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--components-path", "./components"
     ]
    ports:
      - ${DAPR_HTTP_PORT}:${DAPR_HTTP_PORT}
      - ${DAPR_GRPC_PORT}:${DAPR_GRPC_PORT}
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "./.secrets/:/.secrets:ro"
