@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(doerAlias, "Doer", "Person who evidence already done activities.")
System(systemAlias, "SinNet Reports", "https://raport.sin.net.pl")
Rel(doerAlias, systemAlias, "Evidence activities")

' Container(containerAlias, "Label", "Technology", "Optional Description")
' Container(WebApp, "WebApp", "React,Docker", "Default UI for application functionality")


@enduml