# list of images is located @ https://hub.docker.com/_/microsoft-java-jre-headless
# The version should be same as local JDK versio as we use it to run some of local projects in docker containers
FROM mcr.microsoft.com/java/jdk:17u1-zulu-alpine
