trigger:
  branches:
    include:
      - master
  paths:
    include:
      - helm
pool:
  vmImage: 'ubuntu-latest'


- task: HelmDeploy@0
  displayName: Helm package
  inputs:
    command: package
    chartPath: main
    destination: $(Build.ArtifactStagingDirectory)