
variables:
  dockerRegistryServiceConnection: "sinnet-acr"
  imageName: "uservice-customers"
  containerRegistry: "sinnetapps.azurecr.io"
  dockerRepository: onlex-sinnet-reports

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
  - pipeline: helm_CI
    project: sinnet
    source: onlex-sinnet-helm
    trigger: true

stages:
  - stage: deployToProd
    displayName: Deploy HELM Chart to PROD
    jobs:
      - deployment: deployToPrd
        displayName: Deploy to PRD01
        environment: PRD01
        strategy:                  
          runOnce:
            deploy:
              steps:
                - checkout: none
                - download: helm_CI
                  artifact: chart
                - bash: |
                    echo "##vso[task.setvariable variable=var_chart_file_name]$(cat $(Pipeline.Workspace)/helm_CI/chart/chart.config | jq '.chartFileName')"
                - bash: |
                    echo $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                - task: HelmDeploy@0
                  displayName: Helm install
                  inputs:
                    kubernetesServiceEndpoint: PRD01-onlex-sinnet-prd01-1637174649680 
                    command: upgrade
                    install: true
                    chartName: $(Pipeline.Workspace)/helm_CI/chart/$(var_chart_file_name)
                    arguments: -f $(Pipeline.Workspace)/helm_CI/chart/config.yaml
                    releaseName: sinnet-reports
                    namespace: onlex-sinnet-prd01
