
variables:
  dockerRegistryServiceConnection: "sinnet-acr"
  imageName: "uservice-customers"
  containerRegistry: "sinnetapps.azurecr.io"
  dockerRepository: onlex-sinnet-reports

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - helm
pool:
  vmImage: 'ubuntu-latest'

resources:
  - repo: self

resources:
  pipelines:
  - pipeline: webapp_CI
    project: sinnet
    source: onlex-sinnet-webapp
    trigger: true
  - pipeline: webapi_CI
    project: sinnet
    source: onlex-sinnet-webapi2
    trigger: true
  - pipeline: report_CI
    project: sinnet
    source: onlex-sinnet-reports
    trigger: true
  - pipeline: manifest_CI
    project: sinnet
    source: onlex-sinnet-manifest
    trigger: true
  containers:
    - container: webapp
      type: ACR  
      azureSubscription: sinnet-default-manual-arm
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: webapp
    - container: webapi
      type: ACR  
      azureSubscription: sinnet-default-manual-arm
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: webapi
    - container: reports
      type: ACR  
      azureSubscription: sinnet-default-manual-arm
      resourceGroup: sinnet-default-manual
      registry: sinnet
      repository: onlex-sinnet-reports

jobs:
  - job: CICD
    displayName: CI/CD build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: HelmDeploy@0
      displayName: Helm package and deploy
      inputs:
        command: package
        chartPath: helm/main
        azureContainerRegistry: $(dockerRegistryServiceConnection)
    - task: HelmDeploy@0
      displayName: Helm deploy
      inputs:
        connectionType: Azure Resource Manager
        azureSubscriptionEndpoint: sinnet-default-manual-arm
        azureResourceGroup: sinnet-default-manual
        kubernetesCluster: sinnet-microk8s
        namespace: onlex-sinnet-dev01        