resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: "sinnet-acr"
  imageName: "uservice-customers"
  containerRegistry: "sinnetapps.azurecr.io"
  dockerRepository: onlex-sinnet-reports

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - helm
pool:
  vmImage: 'ubuntu-latest'


jobs:
  - job: CICD
    displayName: CI/CD build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: HelmDeploy@0
      displayName: Helm package and deploy
      inputs:
        command: package
        chartPath: helm/main
        azureContainerRegistry: $(dockerRegistryServiceConnection)
        