schema: ../webapi/graphql/src/main/resources/**/*.graphqls
documents: 'src/**/*.graphql'
generates:
  src/Components/.generated/components.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true