# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI static-webapp

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "static-webapp"
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches: [ main, webapp-test ]
    paths: 
      - static-webapp/**
      - /uservice-webapi/api.graphql/**
      - .github/workflows/static-webapp.yml
  pull_request:
    branches: [ main ]
    paths: 
      - static-webapp/**
      - /uservice-webapi/api.graphql/**
      - .github/workflows/static-webapp.yml


jobs:
  
  Build:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 22.12.0
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Generate BUILD_VERSION
        id: build_version
        run: |
          BUILD_DATE=$(date +%Y%m%d)
          BUILD_SHA=${GITHUB_SHA:0:7}
          BUILD_VERSION="${BUILD_DATE}-${BUILD_SHA}"
          echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_OUTPUT
          echo "Generated BUILD_VERSION: ${BUILD_VERSION}"

      - name: Build and run dev container task
        working-directory: static-webapp
        env:
          REACT_APP_BUILD_VERSION: ${{ steps.build_version.outputs.BUILD_VERSION }}
        run: |
            export MY_VERSION=$(cat .version)
            npm config set allow-same-version true
            npm version $MY_VERSION
            npm install
            npm run generate
            npm test
            npm run build

      - name: Store build react binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}-webapp-binaries
          path: static-webapp/build

  DeployProd:
    name: Deploy to PRD01
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')) && github.ref == 'refs/heads/main'
    needs: [ Build ]
    runs-on: ubuntu-22.04
    environment:
      name: prd01
      url: 'https://sinnet.onlex.net'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Restore artifacts from Build
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_id }}-webapp-binaries
          # may be any path, but let's reuse original location
          path: static-webapp/build
          
      - name: Configure runtime settings
        working-directory: static-webapp/build/static/js
        env:
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
        run: |
          echo "Configuring runtime settings for production..."
          
          # Find the main JS bundle
          MAIN_JS=$(ls main.*.js | head -1)
          echo "Found main JS bundle: $MAIN_JS"
          
          # Replace the JSON configuration in the bundle
          sed -i 's|{"applicationInsightsConnectionString":"","environment":"development"}|{"applicationInsightsConnectionString":"'"$APPLICATIONINSIGHTS_CONNECTION_STRING"'","environment":"production"}|g' "$MAIN_JS"
          
          echo "Production configuration updated in $MAIN_JS"
          
      - name: Build And Deploy
        id: builddeploy
        # https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.WEBAPP_PROD_API_TOKEN }}
          # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          # App source code path
          app_location: /static-webapp/build
          # app_build_command: "npm run cibuild"
          # we expect to have built binaries by earlier job
          skip_app_build: true
          # api_location: "" # Api source code path - optional
          # output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  # we have secondary test-view on prod environment, and we are much more flexible with its deployment
  DeployTest:
    # You can start that build using
    # git push origin HEAD:webapp-test --force
    name: Deploy WebApp-Test
    if: (github.event_name == 'push' || github.event_name == 'create') && github.event.ref == 'refs/heads/webapp-test'
    needs: [ Build ]
    runs-on: ubuntu-22.04
    environment:
      name: prd01
      url: 'https://sinnet-test.onlex.net'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Restore artifacts from Build
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_id }}-webapp-binaries
          # may be any path, but let's reuse original location
          path: static-webapp/build
          
      - name: Configure runtime settings for test
        working-directory: static-webapp/build/static/js
        env:
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
        run: |
          echo "Configuring runtime settings for test environment..."
          
          # Find the main JS bundle
          MAIN_JS=$(ls main.*.js | head -1)
          echo "Found main JS bundle: $MAIN_JS"
          
          # Replace the JSON configuration in the bundle
          sed -i 's|{"applicationInsightsConnectionString":"","environment":"development"}|{"applicationInsightsConnectionString":"'"$APPLICATIONINSIGHTS_CONNECTION_STRING"'","environment":"test"}|g' "$MAIN_JS"
          
          echo "Test configuration updated in $MAIN_JS"
          
      - name: Build And Deploy
        # https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.WEBAPP_TEST_API_TOKEN }}
          # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          # App source code path
          app_location: /static-webapp/build
          # app_build_command: "npm run cibuild"
          # we expect to have built binaries by earlier job
          skip_app_build: true
          # api_location: "" # Api source code path - optional
          # output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
