# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub image build for static-webapp

on:
  push:
    branches: [ main ]
    paths: [ static-webapp/**, /uservice-webapi/api.graphql/, .github/workflows/static-webapp.yml ]
  pull_request:
    branches: [ main ]

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          subFolder: static-webapp
          runCmd: |
            export MY_VERSION=$(cat .version)
            cd main
            npm version $MY_VERSION 
            npm install
            npm run generate
            npm run build
      - name: Store build react binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${$GITHUB_RUN_ID}-webapp-binaries
          path: static-webapp/main/build

  DeployDev:
    name: Deploy to DEV01
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: dev01
      url: 'https://sinnet-dev01.onlex.net'
    steps:
      - name: Deploy
        run: echo I am deploying!
      - name: Restore artifacts from Build
        uses: actions/download-artifact@v2
        with:
          name: ${$GITHUB_RUN_ID}-webapp-binaries
          # may be any path, but let's reuse original location
          path: static-webapp/main/build
      - name: Build And Deploy
        id: builddeploy
        # https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          # App source code path
          app_location: /static-webapp/main/build
          # app_build_command: "npm run cibuild"
          # we expect to have built binaries by earlier job
          skip_app_build: true
          # api_location: "" # Api source code path - optional
          # output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  DeployUat:
    name: Deploy to PROD
    if: github.event.ref == 'refs/heads/main'
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: prod1
      url: 'https://sinnet.onlex.net'
    steps:
      - name: Deploy
        run: echo I am deploying!

