# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#registry_package

name: Handle latest container version

on:
    registry_package:
      types: [published]

# read latest tak and save to file
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest tag
        run: |
          echo ::set-output name=tag::$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
        id: get_tag
      - name: Save tag to file
        run: |
          echo "${{ steps.get_tag.outputs.tag }}" > tag.txt
      - name: Show thw tag
        run: |
          cat tag.txt
      # - name: Commit tag file
      #   run: |
      #     git config --local user.email "
